### ISSUE TITLE
x64 bit compiler

### ISSUE THREAD

**Issue by LifeIsHex** [TheLazyTomcat/lib.BitOps#1]
Hey,
Here is the problem with win64 bit compiling, I guess you might miss it.

Function BTS(var Value: UInt64; Bit: Integer): Boolean;
{$IFNDEF PurePascal}
asm
{$IFDEF x64}
  {$IFDEF Windows}
    AND   RDX, 63
    BTS   dword ptr [RCX], RDX       ==> Error here
  {$ELSE}
    AND   RSI, 63
    BTS   dword ptr [RDI], RSI          ==> Error here
  {$ENDIF}
{$ELSE}
    AND   EDX, 63
    CMP   EDX, 32
    JAE   @TestHigh

    BTS   dword ptr [Value], EDX
    JMP   @SetResult

  @TestHigh:
    AND   EDX, 31
    BTS   dword ptr [EAX + 4], EDX
{$ENDIF}
  @SetResult:
    SETC  AL
end;

BTS   dword ptr [RCX], RDX => Error
I think we have to use qword here (refer to Value: UInt64;).

same error with :
Function BTR(var Value: UInt64; Bit: Integer): Boolean;
Function BTC(var Value: UInt64; Bit: Integer): Boolean;

Bests,
Mahdi

**Comment by TheLazyTomcat** [comment]
Many thanks for reporting this bug!
You are correct, there should be `qword`, not `dword`. I will push correction in few hours.

**Comment by TheLazyTomcat** [comment]
Should be corrected by now, but since I don't have 64bit Delphi compiler, I cannot verify it - so if anyone can confirm the current version is working, I would appreciate it, thanks! For now I will leave this open in case anyone reports anything.

A small technical note - the code was actually working correctly (bit strings, bit base, bit offset and such... read the Intel documentation on BT(S/RC) instructions), though it was not intended that way. Even if `byte ptr` was there it would work, it just seems Delphi are a little too strict here.

**Comment by LifeIsHex** [comment]
I use it with the 64-bit compiler; the only problem was the qword. So I guess it works fine now.
